INSERT INTO imovels (
    titulo,
    descricao,
    endereco,
    finalidade,
    valor,
    quartos,
    banheiros,
    garagem,
    corretor,
    created_at,
    updated_at
) VALUES
(
    'Apartamento Luxo Centro',
    'Apartamento com vista panorâmica, excelente localização e acabamento premium.',
    'Rua das Flores, 123, Centro, São Paulo, SP',
    'Venda',
    1500000.00,
    3,
    2,
    1,
    'João Silva',
    NOW(),
    NOW()
),
(
    'Casa Familiar Bairro Verde',
    'Casa ampla, com quintal, próxima a escolas e supermercados.',
    'Av. Brasil, 456, Bairro Verde, Curitiba, PR',
    'Locação',
    3500.00,
    4,
    3,
    1,
    'Maria Souza',
    NOW(),
    NOW()
),
(
    'Kitnet Econômica Zona Norte',
    'Kitnet prática para estudantes ou solteiros.',
    'Rua Aurora, 789, Zona Norte, Porto Alegre, RS',
    'Locação',
    1200.00,
    1,
    1,
    0,
    'Carlos Pereira',
    NOW(),
    NOW()
),
(
    'Cobertura Duplex Vila Olímpia',
    'Cobertura duplex moderna com área gourmet e piscina privativa.',
    'Rua Olimpíadas, 321, Vila Olímpia, São Paulo, SP',
    'Venda',
    2500000.00,
    4,
    4,
    1,
    'Ana Martins',
    NOW(),
    NOW()
),
(
    'Sítio Rústico Interior',
    'Sítio com pomar, lago e área para criação de animais.',
    'Rodovia KM 45, Zona Rural, Itapetininga, SP',
    'Venda',
    800000.00,
    3,
    2,
    1,
    'Eduardo Costa',
    NOW(),
    NOW()
),
(
    'Loft Moderno Centro Histórico',
    'Loft totalmente reformado em prédio histórico, ideal para investidores.',
    'Rua do Comércio, 12, Centro Histórico, Salvador, BA',
    'Venda',
    550000.00,
    1,
    1,
    0,
    'Fernanda Lima',
    NOW(),
    NOW()
),
(
    'Sobrado Geminado Zona Leste',
    'Sobrado novo com fácil acesso a transporte público.',
    'Rua das Acácias, 250, Zona Leste, São Paulo, SP',
    'Locação',
    4500.00,
    3,
    2,
    1,
    'Paulo Mendes',
    NOW(),
    NOW()
),
(
    'Chácara Espaçosa em Condomínio',
    'Chácara com piscina, churrasqueira e casa de hóspedes.',
    'Estrada Municipal, 89, Condomínio Paraíso, Sorocaba, SP',
    'Venda',
    1200000.00,
    5,
    4,
    1,
    'Roberta Souza',
    NOW(),
    NOW()
);
